"""add relationship to users

Revision ID: 7027f30d14e9
Revises: f5ff627a33d0
Create Date: 2023-06-13 22:17:00.505738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7027f30d14e9'
down_revision = 'f5ff627a33d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
