"""add weather source table

Revision ID: 99208cc06c82
Revises: 7027f30d14e9
Create Date: 2023-06-14 18:22:42.958983

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '99208cc06c82'
down_revision = '7027f30d14e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_source',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('location_name', sa.String(length=128), nullable=False),
    sa.Column('source_name', sa.String(length=48), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_weather_source_location1', 'weather_source', ['location'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_weather_source_location1', table_name='weather_source', postgresql_using='gist')
    op.drop_table('weather_source')
    # ### end Alembic commands ###
